# SAGA ancillary data collation
###  Importing programs and reading in SAGA spectral data

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from astropy.table import Table, join , Column, vstack
import astropy
from astropy.io import ascii
import csv
from astropy.coordinates import SkyCoord
from astropy import units as u
import os
import pandas as pd


#opening spectral data
spec_data_all = Table.read('saga_spectra_clean.fits')
spec_data_all #table name for spec data

<Table masked=True length=68635>
       OBJID              RA      ...   SPEC_HA_EW  SPEC_HA_EWERR 
       int64           float64    ...    float64       float64    
------------------- ------------- ... ------------- --------------
1237648721752687341 145.879343509 ...         -99.0          -99.0
1237648721215750163 145.737188848 ...         -99.0          -99.0
1237650796219728076  145.49930471 ...         -99.0          -99.0
1237648721752359009 145.145128066 ...           0.0            0.0
1237650796756730414 145.816662813 ...         -99.0          -99.0
1237648722289361071 145.445194354 ...         -99.0          -99.0
1237650795682922788 145.669169134 ... 9.84451770782 0.768112957478
1237650795682988326 145.892442886 ...         -99.0          -99.0
1237650796219728040 145.464543343 ...         -99.0          -99.0
1237650796219793814 145.600551406 ...         -99.0          -99.0
                ...           ... ...           ...            ...
1237668336320971571 234.465631623 ...         -99.0          -99.0
1237665565541597964 233.801791932 ...         -99.0          -99.0
1237665566078468677 233.937756668 ...         -99.0          -99.0
1237665566078599695 234.309236917 ...         -99.0          -99.0
1237665566078665629 234.426728971 ...         -99.0          -99.0
1237668336320971566 234.470851598 ...         -99.0          -99.0
1237668336320971184 234.474859737 ...         -99.0          -99.0
1237665565541597409 233.793232948 ...           0.0            0.0
1237665566078468569 233.953447622 ...         -99.0          -99.0
1237665566078665274 234.339336362 ...         -99.0          -99.0

In [3]:
#remember to compare to spec_data_all and then check against sdss...compare overall matches against
#both spec_data tables

#making cuts so only SAGA + sdss id'ed satallite galaxies appear-eriks suggestion
spec_data = spec_data_all[(spec_data_all['SATS']==1)&(spec_data_all['REMOVE']==-1)]
spec_data

<Table masked=True length=167>
       OBJID              RA      ...   SPEC_HA_EW  SPEC_HA_EWERR 
       int64           float64    ...    float64       float64    
------------------- ------------- ... ------------- --------------
1237648722289295527 145.320962664 ... 26.0362949371  0.72926735878
1237653612647678107  139.49713703 ... 9.95044326782 0.490148693323
1237653613184680084  139.44430792 ...           0.0            0.0
1237654382515388427 139.189595559 ...  80.882850647  1.08989155293
1237654381982777375 154.231241268 ...           0.0            0.0
1237655368744632621  155.66592215 ...  43.444606781  1.84664130211
1237654381982777687 154.300660995 ...           0.0            0.0
1237657607497318756 123.243173206 ... 16.3851947784 0.566546261311
1237657607497515484 123.649897556 ... 36.2241401672  2.03956627846
1237658310795591687 193.681402422 ...           0.0            0.0
                ...           ... ...           ...            ...
1237654879127666883 217.818940474 ...  6.0990562439 0.716566503048
1237655369832267945  217.94533575 ... 8.07443714142 0.690588712692
1237661386533175309 219.969004509 ... 14.6017227173 0.802008509636
1237661416603975998 219.422236629 ... 19.5342693329  2.58787894249
1237661385996304558 219.746469375 ... 4.18224000931 0.397005200386
1237661416603910425 219.190054522 ...           0.0            0.0
1237648721248845970 221.316115836 ... 6.01830720901  0.51613008976
1237654399164219640 222.900268358 ...           0.0            0.0
1237665566078402826 233.787037531 ...           0.0            0.0
1237665565541728490 234.132926177 ...  4.2713060379 0.541258990765

# Palomar Data
## Opening data WITH coords 
#### May17 w/coords

In [4]:
with open('targs_may17.csv', newline='') as f: #file for matching to palomar links data
    ID=[];RA=[];DEC=[];EPOCH=[];idk1=[];idk2=[];idk3=[]
    reader = csv.reader(f)
    for row in reader:
        list1 = row[0];ID.append(list1)
        list2 = row[1];RA.append(list2)
        list3 = row[2];DEC.append(list3)
        list4 = row[3];EPOCH.append(list4)
        list5 = row[4];idk1.append(list5)
        list6 = row[5];idk2.append(list6)
        list7 = row[6];idk3.append(list7)
print (type (idk3))

<class 'list'>


In [5]:
#this will convert all those above lists into table columns
coord_data_may17=Table([ID,RA,DEC,EPOCH,idk1,idk2,idk3], names=('ID','RA','DEC','EPOCH','idk1','idk2','idk3'))
#coord_data_may17 #Palomar link coords table

#### May15 w/ coords

In [6]:
with open('targs_may15.csv', newline='') as f:
#f = open('targs_may15.csv')
    ID=[];RA=[];DEC=[];EPOCH=[];idk1=[];idk2=[];idk3=[];idk4=[]
#try:
    reader = csv.reader(f)
    for row in reader:
        list1 = row[0];ID.append(list1)
        list2 = row[1];RA.append(list2)
        list3 = row[2];DEC.append(list3)
        list4 = row[3];EPOCH.append(list4)
        list5 = row[4];idk1.append(list5)
        list6 = row[5];idk2.append(list6)
        list7 = row[6];idk3.append(list7)
        #list8 = row[7];idk4.append(list8)
#ommitted list 8 b/c having index range bugs b/c comments arent in every column and dont *think* theyre needed
#print (type (idk3))
#print (len(idk2))-------------------------------------

#this will convert all those above lists into table columns

coord_data_may15=Table([ID,RA,DEC,EPOCH,idk1,idk2,idk3], names=('ID','RA','DEC','EPOCH','idk1','idk2','idk3'))
#this is the table name of data Im getting coords from to match to handlog
#coord_data_may15

#### Nov15 w/ coords

In [7]:
with open('targs_nov15.csv', newline='') as f:
    ID=[];RA=[];DEC=[];EPOCH=[];idk1=[];idk2=[];idk3=[];idk4=[]
    reader = csv.reader(f)
    for row in reader:
        list1 = row[0];ID.append(list1)
        list2 = row[1];RA.append(list2)
        list3 = row[2];DEC.append(list3)
        list4 = row[3];EPOCH.append(list4)
        list5 = row[4];idk1.append(list5) #idk b/c idk what to call those columns
        list6 = row[5];idk2.append(list6)
        list7 = row[6];idk3.append(list7)
        #list8 = row[7];idk4.append(list8) #still cant include b/c "list index out of range" error
#ommitted list 8 b/c having index range bugs b/c comments arent in every column and dont *think* theyre needed
#print (type (idk3))
#print (len(idk2))

#this will convert all those above lists into table columns

coord_data_nov15=Table([ID,RA,DEC,EPOCH,idk1,idk2,idk3], names=('ID','RA','DEC','EPOCH','idk1','idk2','idk3'))
#this is the table name of data Im getting coords from to match to handlog
#coord_data_nov15

## Opening Palomar data W/O coords
#### LINK-may17 w/o coords

In [8]:
#opening the palomar link data AFTER saved into ONE SHEET
import pandas as pd
link_data_all = pd.read_excel('Palomar_Run_May_2017_onesheet.xlsx')

Table.from_pandas(link_data_all) #this is a table of all data from palomar link
#note that date transferred in with time...amend this


#extracting only the columns I'll need
date = link_data_all['Date']
target = link_data_all['ID']
instrument = link_data_all['Instrument']
exp_time = link_data_all['exp time']

link_data_names_may17 = Table([date, target, instrument, exp_time], names=('Date', 'ID', 'Instrument', 'exp_time'))
#link_data_names_may17

In [9]:
#this fixes dtypes for id to enable matching by names later
#tried to also fix date but cant for now...try again later
col1 = Column(link_data_names_may17['Date'], name='Date', dtype=str)
col2 = Column(link_data_names_may17['ID'], name='ID', dtype=str)
link_data_names_may17['ID'] = col2
link_data_names_may17['Date'] = col1
#link_data_names_may17

#### May15 handlog data w/o coords 

In [10]:
may15_data = ascii.read('handlogs_May15_MYCOPYfinal.txt') 

#### Nov15 handlog data w/o coords

In [11]:
nov15_data = ascii.read('handlogs_Nov15.txt') 

## Matching Palomar data w/ & w/o coords via Names
#### May15-name matched

In [12]:
#first lets match the names between these two tables to get the coords
mergedata=(join(coord_data_may15, may15_data, keys=['ID']))
names_may15_palomar = mergedata['ID','RA','DEC','Date','exp_time']

#second adding a column so we know what instrument was used
names_may15_palomar['Instrument'] = 'Palomar_Double_Spec'

names_may15_palomar #this is the table of final info i need to match by coords to the spec data

<Table masked=True length=66>
    ID           RA           DEC         Date  exp_time      Instrument    
  str40        str13         str14        str7  float64         str19       
---------- ------------- -------------- ------- -------- -------------------
BD+28 4211   21 51 11.02     28 51 50.4 5/10/15     60.0 Palomar_Double_Spec
BD+28 4211   21 51 11.02     28 51 50.4 5-12-15     60.0 Palomar_Double_Spec
BD+28 4211   21 51 11.02     28 51 50.4 5-12-15     60.0 Palomar_Double_Spec
BD+28 4211   21 51 11.02     28 51 50.4 5-11-15     60.0 Palomar_Double_Spec
BD+28 4211   21 51 11.02     28 51 50.4 5-13-15     60.0 Palomar_Double_Spec
BD+33 2642   15 51 59.89    +32 56 54.3 5-13-15     45.0 Palomar_Double_Spec
BD+33 2642   15 51 59.89    +32 56 54.3 5-11-15     60.0 Palomar_Double_Spec
BD+33 2642   15 51 59.89    +32 56 54.3 5/10/15     60.0 Palomar_Double_Spec
  Feige 34   10 39 36.74    +43 06 09.3 5/10/15     60.0 Palomar_Double_Spec
  Feige 34   10 39 36.74    +43 06 09.3 5-11-15     60.0 Palomar_Double_Spec
       ...           ...            ...     ...      ...                 ...
     y1606 13 12 29.0674  -3 23 22.1416 5-12-15    600.0 Palomar_Double_Spec
     y1635 13 23 04.0285 +39 09 32.5493 5-11-15    600.0 Palomar_Double_Spec
     y2367 16 23 26.8091 +41 54 02.5559 5-12-15    600.0 Palomar_Double_Spec
     y2457 16 43 27.3865  -8 02 57.6332 5-12-15    600.0 Palomar_Double_Spec
     y2483 16 45 48.8346 +46 47 25.5353 5/10/15    600.0 Palomar_Double_Spec
     y2483 16 45 48.8346 +46 47 25.5353 5-11-15    600.0 Palomar_Double_Spec
     y2483 16 45 48.8346 +46 47 25.5353 5-13-15    600.0 Palomar_Double_Spec
     y2483 16 45 48.8346 +46 47 25.5353 5-12-15    400.0 Palomar_Double_Spec
      y802  8 46 15.0982  +2 15 53.4443 5/10/15    600.0 Palomar_Double_Spec
      y877  9 08 37.1194  +5 17 37.4082 5-12-15    600.0 Palomar_Double_Spec

#### LINK-may17-name matched

In [13]:
#fixing instrument column
link_data_names_may17['ID'][157] #this returns 'ContFlat' so its the right area..literally counted rows
#making instrument distinction beginning after ID = contflat / contbar area
link_data_names_may17['Instrument'][0:157] = 'Palomar_Double_Spec'
link_data_names_may17['Instrument'][157::] = 'Palomar_CWI'
#link_data_names_may17

#first lets match the names between these two tables to get the coords
mergedata2=(join(coord_data_may17, link_data_names_may17, keys=['ID']))
names_may17_palomar = mergedata2['ID','RA','DEC','Date','Instrument','exp_time']

#second adding a column so we know what instrument was used
#names_may17_palomar['Instrument'] = 'Palomar_Double_Spec'
names_may17_palomar

<Table length=67>
           ID                 RA      ...      Instrument     exp_time
         str100             str13     ...        object       float64 
----------------------- ------------- ... ------------------- --------
    48721248845970-Dune 14:45:15.8678 ... Palomar_Double_Spec    600.0
   50372092690464-Alice 12:01:10.9061 ...         Palomar_CWI   1200.0
   50372092690464-Alice 12:01:10.9061 ...         Palomar_CWI    960.0
   50372092690464-Alice 12:01:10.9061 ...         Palomar_CWI     90.0
   50372092690464-Alice 12:01:10.9061 ...         Palomar_CWI     90.0
57607497318756-StarTrek  8:12:58.3616 ... Palomar_Double_Spec    600.0
57607497515484-StarTrek  8:14:35.9754 ... Palomar_Double_Spec    600.0
 62224092496776-Odyssey 16:32:46.8885 ... Palomar_Double_Spec    900.0
 62662147310256-Odyssey 16:31:18.2141 ...         Palomar_CWI     90.0
 62662147310256-Odyssey 16:31:18.2141 ...         Palomar_CWI     90.0
                    ...           ... ...                 ...      ...
                  HZ 43   13 16 21.85 ... Palomar_Double_Spec     90.0
                M-01-01  18:07:20.483 ... Palomar_Double_Spec    200.0
                M-01-01  18:07:20.483 ... Palomar_Double_Spec    200.0
                M-01-04  18:13:19.064 ... Palomar_Double_Spec    200.0
                M-01-04  18:13:19.064 ... Palomar_Double_Spec    200.0
                M-01-04  18:13:19.064 ... Palomar_Double_Spec    100.0
                M-01-04  18:13:19.064 ... Palomar_Double_Spec    200.0
                M-01-04  18:13:19.064 ... Palomar_Double_Spec    200.0
        OBrother_nospec 22:22:47.1508 ... Palomar_Double_Spec    500.0
             Ody_nospec 16:32:11.7432 ... Palomar_Double_Spec    600.0

#### Nov15-name matched

In [14]:
#first lets match the names between these two tables to get the coords
mergedata_nov15=(join(coord_data_nov15, nov15_data, keys=['ID']))
names_nov15_palomar = mergedata_nov15['ID','RA','DEC','Date','Instrument','exp_time']
names_nov15_palomar

<Table masked=True length=15>
    ID          RA         DEC        Date       Instrument        exp_time   
  str44       str13       str14       str7         str19            str14     
---------- ----------- ------------ ------- ------------------- --------------
    AnaK_1 23 37 24.14 +00 23 26.89 11/6/15 Palomar_Double_Spec            600
    AnaK_1 23 37 24.14 +00 23 26.89 11/6/15 Palomar_Double_Spec            600
    AnaK_2 23 36 46.86 +00 37 24.33 11/6/15 Palomar_Double_Spec            900
 Beowulf_1 09 06 00.93 +25 28 11.70 11/8/15 Palomar_Double_Spec            900
 Beowulf_2 09 07 08.29 +25 20 33.27 11/8/15 Palomar_Double_Spec            300
 Beowulf_3 09 06 00.94 +25 22 33.58 11/8/15 Palomar_Double_Spec            600
 Beowulf_4 09 06 12.49 +25 47 01.04 11/8/15 Palomar_Double_Spec 600(420oflost)
 Catch22_1 23 14 47.20 +04 38 23.84 11/8/15 Palomar_Double_Spec            600
 Catch22_2 23 15 06.46 +04 22 23.51 11/8/15 Palomar_Double_Spec            600
 Catch22_3 23 15 29.81 +04 36 47.74 11/8/15 Palomar_Double_Spec            600
  G191-B2B  05 05 30.6    +52 49 54 11/5/15 Palomar_Double_Spec             60
  G191-B2B  05 05 30.6    +52 49 54 11/5/15 Palomar_Double_Spec             60
   HD65583 08 00 32.13 +29 12 44.48 11/5/15 Palomar_Double_Spec            999
   Iliad_1 22 52 21.12 -05 44 40.22 11/8/15 Palomar_Double_Spec            660
MobyDick_1 09 58 44.92 +32 43 12.96 11/6/15 Palomar_Double_Spec            900

# Keck Deimos Data
#### Sept 23,2014 deimos data w/coords

In [15]:
#opens & splits via new lines & blank spaces---outputs a list
#NOTE: had to edit original data fixing spaces inside columns in excel as csv 
def generate_values_for_filename(filename):
    with open(filename) as f:
        for line in f:
            for row in line.split('\n'): #this splits by line
                #print(row)
                for word in row.split(' '): #this splits by blank space
                    #print(word)
                    yield word

In [16]:
#using above fcn to open & split datafile               
sept_values = list(generate_values_for_filename('Sept2014_deimos_MYCOPY.csv'))
#print ('start',sept_values, 'end')

#naming arrays for columns I'll need
obj_sept=np.array(sept_values[17::16])
ra_sept=np.array(sept_values[20::16])
dec_sept=np.array(sept_values[21::16])
exp_time_sept=np.array(sept_values[28::16]) #figure out column/rows valueslike above


#print (exp_time_sept)
#print (obj)
#print ('testing-Below is the RAs')
#print (ra)
#print ('testing-Below is the DECs')
#print (type(dec[0])) #they are strings

#making arrays into a table
sept14_deimos_table = Table([obj_sept, ra_sept, dec_sept, exp_time_sept], names=('ID','RA','DEC','Exp_time'))
sept14_deimos_table['Instrument'] ='Keck_deimos'
sept14_deimos_table['Date'] ='9-23-2014'

sept14_deimos_table

<Table length=115>
             ID                   RA         DEC     ...  Instrument    Date  
           str29                str11       str11    ...    str11       str9  
---------------------------- ----------- ----------- ... ----------- ---------
     ""g191b2b_driftscan_6"" 03:52:00.00 +45:00:00.0 ... Keck_deimos 9-23-2014
""Direct_image_mask_And9m2"" 03:52:00.00 +45:00:00.0 ... Keck_deimos 9-23-2014
 ""Direct_image_mask_A19r2"" 03:52:00.00 +45:00:00.0 ... Keck_deimos 9-23-2014
""Direct_image_mask_19str2"" 03:52:00.00 +45:00:00.0 ... Keck_deimos 9-23-2014
 ""Direct_image_mask_A19r1"" 03:52:00.00 +45:00:00.0 ... Keck_deimos 9-23-2014
""Direct_image_mask_19str1"" 03:52:00.00 +45:00:00.0 ... Keck_deimos 9-23-2014
""Direct_image_mask_And9m1"" 03:52:00.00 +45:00:00.0 ... Keck_deimos 9-23-2014
  ""Direct_imag_mask_a29_2"" 03:52:00.00 +45:00:00.0 ... Keck_deimos 9-23-2014
       ""Focus_loop_R_dome"" 03:52:00.00 +45:00:00.0 ... Keck_deimos 9-23-2014
       ""Focus_loop_R_dome"" 03:52:00.00 +45:00:00.0 ... Keck_deimos 9-23-2014
                         ...         ...         ... ...         ...       ...
             ""A19r1_align"" 00:19:39.57 +35:11:19.3 ... Keck_deimos 9-23-2014
            ""And9m2_align"" 00:52:57.16 +43:11:49.9 ... Keck_deimos 9-23-2014
            ""And9m2_align"" 00:52:57.19 +43:11:48.7 ... Keck_deimos 9-23-2014
                      And9m2 00:52:57.20 +43:11:48.7 ... Keck_deimos 9-23-2014
                      And9m2 00:52:57.20 +43:11:48.7 ... Keck_deimos 9-23-2014
            n132339_satcand2 02:37:46.03 -00:23:23.5 ... Keck_deimos 9-23-2014
            n132339_satcand2 02:37:46.03 -00:23:23.5 ... Keck_deimos 9-23-2014
            n132339_satcand1 02:36:28.59 -00:58:28.9 ... Keck_deimos 9-23-2014
            n132339_satcand1 02:36:28.59 -00:58:28.9 ... Keck_deimos 9-23-2014
                  m283_ghost 02:21:04.40 +29:23:50.7 ... Keck_deimos 9-23-2014

#### May 17, 2015 deimos data w/coords

In [17]:
#using above fcn to open & split datafile               
may_values = list(generate_values_for_filename('May2015_deimos_MYCOPY.csv'))

#naming arrays for columns I'll need
obj_may=np.array(may_values[18::17]) #numbers mean start there then repeat every 17th item creating column structure
ra_may=np.array(may_values[22::17])
dec_may=np.array(may_values[23::17])
exp_time_may=np.array(may_values[30::17]) #figure out column/rows valueslike above

#print (exp_time_may)
#making arrays into a table
may15_deimos_table = Table([obj_may, ra_may, dec_may, exp_time_may], names=('ID','RA','DEC','Exp_time'))
may15_deimos_table['Instrument'] ='Keck_deimos'
may15_deimos_table['Date'] ='5-17-2015'

may15_deimos_table

<Table length=101>
             ID                  RA         DEC     ...  Instrument    Date  
           str27               str11       str11    ...    str11       str9  
--------------------------- ----------- ----------- ... ----------- ---------
         ""212915A1_align"" 04:29:24.00 +00:03:32.4 ... Keck_deimos 5-17-2015
""Direct_image_mask_Herc1"" 04:29:24.00 +00:03:32.4 ... Keck_deimos 5-17-2015
""Direct_image_mask_Herc2"" 04:29:24.00 +00:03:32.4 ... Keck_deimos 5-17-2015
""Direct_image_mask_Herc3"" 04:29:24.00 +00:03:32.4 ... Keck_deimos 5-17-2015
""Direct_image_mask_LeoV1"" 04:29:24.00 +00:03:32.4 ... Keck_deimos 5-17-2015
""Direct_image_mask_LeoV2""  !KeyError!  !KeyError! ... Keck_deimos 5-17-2015
""Direct_image_mask_LeoV3"" 00:00:00.00 +00:00:00.0 ... Keck_deimos 5-17-2015
      ""Focus_loop_R_dome"" 03:52:00.00 +45:00:00.0 ... Keck_deimos 5-17-2015
      ""Focus_loop_R_dome"" 03:52:00.00 +45:00:00.0 ... Keck_deimos 5-17-2015
      ""Focus_loop_R_dome"" 03:52:00.00 +45:00:00.0 ... Keck_deimos 5-17-2015
                        ...         ...         ... ...         ...       ...
            ""Herc3_align"" 16:30:40.93 +12:49:36.5 ... Keck_deimos 5-17-2015
            ""Herc3_align"" 16:30:40.93 +12:49:36.5 ... Keck_deimos 5-17-2015
              ""Odyssey_4"" 16:32:36.50 +19:48:34.2 ... Keck_deimos 5-17-2015
              ""Odyssey_4"" 16:32:36.50 +19:48:34.2 ... Keck_deimos 5-17-2015
              ""Odyssey_4"" 16:32:36.50 +19:48:34.2 ... Keck_deimos 5-17-2015
                 ""AnaK_1"" 23:37:24.17 +00:23:24.1 ... Keck_deimos 5-17-2015
                 ""AnaK_1"" 23:37:24.17 +00:23:24.1 ... Keck_deimos 5-17-2015
                 ""AnaK_2"" 23:36:47.34 +00:37:33.1 ... Keck_deimos 5-17-2015
              ""BD+284211"" 21:51:10.94 +28:52:05.0 ... Keck_deimos 5-17-2015
              ""BD+284211"" 21:51:10.94 +28:52:04.9 ... Keck_deimos 5-17-2015

#### Mar/Apr 2016 deimos data w/coords ---- had NO EXP_TIMES

In [18]:
#faster to just edit the data file into a txt and get rid of "good", "twilight", "nothing", etc comments
marapr16_data = ascii.read('MarApr2016_deimos.txt') 
dcol_1 = np.array(marapr16_data['ID'])
dcol_2 = np.array(marapr16_data['RA'])
dcol_3 = np.array(marapr16_data['DEC'])

#creating the table using columns above
marapr2016_deimos = Table([dcol_1, dcol_2, dcol_3], names=('ID', 'RA', 'DEC'))
marapr2016_deimos['Instrument'] = 'Keck_deimos'
marapr2016_deimos

<Table length=55>
 ID       RA         DEC      Instrument
str4    str11       str11       str11   
---- ----------- ----------- -----------
 ST3 08:11:38.85 +36:12:02.5 Keck_deimos
 ST3 08:11:38.85 +36:12:02.5 Keck_deimos
 ST3 08:11:38.85 +36:12:02.5 Keck_deimos
 MD1 10:00:35.00 +32:34:00.9 Keck_deimos
 MD1 10:00:35.00 +32:34:00.9 Keck_deimos
 MD1 10:00:35.00 +32:34:00.9 Keck_deimos
 MD3 09:56:01.02 +32:13:44.4 Keck_deimos
 MD3 09:56:01.02 +32:13:44.4 Keck_deimos
 MD3 09:56:01.02 +32:13:44.4 Keck_deimos
 MD4 09:59:23.88 +31:47:14.2 Keck_deimos
 ...         ...         ...         ...
 ST2 08:13:09.00 +36:16:41.6 Keck_deimos
 ST1 08:14:06.20 +36:08:59.6 Keck_deimos
 ST1 08:14:06.20 +36:08:59.6 Keck_deimos
 ST1 08:14:06.20 +36:08:59.6 Keck_deimos
AnaK 23:37:07.80 +00:12:40.6 Keck_deimos
AnaK 23:37:07.80 +00:12:40.6 Keck_deimos
AnaK 23:37:10.00 +00:12:15.8 Keck_deimos
AnaK 23:37:10.00 +00:12:15.8 Keck_deimos
Dune 14:45:36.00 -00:20:40.5 Keck_deimos
Dune 14:45:36.00 -00:20:40.5 Keck_deimos

#### Sept 2013 deimos data logs 1 & 2

In [19]:
#these were PDFs I digitized -- combined logs 1& 2 b/c short
deimos_log1n2_data = pd.read_excel('Sept13_Deimos_log_1and2.xlsx')

Table.from_pandas(deimos_log1n2_data)
first = deimos_log1n2_data['Date']
second = deimos_log1n2_data['ID']
third = deimos_log1n2_data['RA']
fourth = deimos_log1n2_data['DEC']
fifth = deimos_log1n2_data['Exp_time']
sixth = deimos_log1n2_data['Instrument']

sept13_deimos_table = Table([first, second, third, fourth, fifth, sixth], names=('Date','ID','RA','DEC','Exp_time','Instrument'))

#this section converts all objects into strings for column data types-makes matching easier later
col_date = Column(sept13_deimos_table['Date'], dtype=str)
sept13_deimos_table['Date'] = col_date
col_id = Column(sept13_deimos_table['ID'], dtype=str)
sept13_deimos_table['ID'] = col_id
col_ra = Column(sept13_deimos_table['RA'], dtype=str)
sept13_deimos_table['RA'] = col_ra
col_dec = Column(sept13_deimos_table['DEC'], dtype=str)
sept13_deimos_table['DEC'] = col_dec
col_exptime = Column(sept13_deimos_table['Exp_time'], dtype=str)
sept13_deimos_table['Exp_time'] = col_exptime
col_inst = Column(sept13_deimos_table['Instrument'], dtype=str)
sept13_deimos_table['Instrument'] = col_inst

#this is the final table
sept13_deimos_table

<Table length=36>
  Date         ID            RA         DEC      Exp_time Instrument
  str8       str21         str11       str12      str21      str4   
-------- -------------- ----------- ------------ -------- ----------
9-7-2013       Penelope 16:31:20.87 +20:08:41.0       100       Keck
9-7-2013       Penelope 16:31:20.87 +20:08:41.0       300       Keck
9-7-2013       Penelope 16:31:20.87 +20:08:41.0       300       Keck
9-7-2013     Telemachus 16:33:37.48  +19:54:28.2      150       Keck
9-7-2013          Circe 16:32:02.97  +19:42:10.8      150       Keck
9-7-2013          Circe 16:32:02.97  +19:42:10.8      200       Keck
9-7-2013     Polyphemus 16:33:21.81  +19:27:14.6      200       Keck
9-7-2013 Calypso_aquire 16:32:48.81  +19:46:42.8       30       Keck
9-7-2013 Calypso_aquire 16:32:48.81  +19:46:42.8       90       Keck
9-7-2013      Calypso   16:32:48.69  +19:46:42.9      200       Keck
     ...            ...         ...          ...      ...        ...
9-8-2013     Polyphemus 16:33:16.78  +19:31:49.4      150       Keck
9-8-2013     Polyphemus 16:33:16.78  +19:31:49.4      200       Keck
9-8-2013          Peg_4 23:28:49.62  +14:40:18.2     1000       Keck
9-8-2013          Peg_4 23:28:49.62  +14:40:18.2      850       Keck
9-8-2013          Peg_5 23:28:43.67  +14:43:04.4      400       Keck
9-8-2013         IC10-4 00:20:37.33  +59:17:06.5      800       Keck
9-8-2013         IC10-4 00:20:37.33  +59:17:06.5      640       Keck
9-8-2013         LGS3_1 01:04:02.73  +21:54:08.5      600       Keck
9-8-2013       G191-B2B 05:05:44.50  +52:50:39.3       20       Keck
9-8-2013       G191-B2B 05:05:44.50  +52:50:39.3       60       Keck

# Arecibo Radio data

In [20]:
radio_data = pd.read_excel('saga_hi_search.xlsx')
#making the excel sheet into a table so easier to work with when comparing ra & dec
a = radio_data['name']
b = radio_data['ra']
c = radio_data['dec']
d = radio_data['HI_data_source']

radio_data_table = Table([a, b, c, d], names=('ID','RA','DEC', 'HI_data_source')) #, meta={'name': 'first table'})

#fixing id and HI columns to be strings instead of objects to make matching easier later
colid = Column(radio_data_table['ID'], dtype=str)
radio_data_table['ID'] = colid
colHI = Column(radio_data_table['HI_data_source'], dtype=str)
radio_data_table['HI_data_source'] = colHI

#adding these columns to the table
radio_data_table['Instrument'] = ('Arecibo_radio') #probably need to change name but for now radio is generic 
radio_data_table['Date'] = ('unknown') #get from erik - cant find in file
radio_data_table #table name of radio data
#these should all be SAGA satellites so might not need RA & DEC

<Table length=44>
     ID        RA     DEC    ...   Instrument    Date 
   str11    float64 float64  ...     str13       str7 
----------- ------- -------- ... ------------- -------
 Bandamanna 1.12966   20.718 ... Arecibo_radio unknown
HarryPotter 20.2853  17.6022 ... Arecibo_radio unknown
HarryPotter 20.3285  17.7539 ... Arecibo_radio unknown
HarryPotter 20.5363  17.5281 ... Arecibo_radio unknown
HarryPotter 20.7769  17.8914 ... Arecibo_radio unknown
     Narnia 39.5362  -1.3967 ... Arecibo_radio unknown
     Narnia 39.9255 -1.41874 ... Arecibo_radio unknown
   StarTrek 123.243  36.1984 ... Arecibo_radio unknown
   StarTrek  123.65  36.4344 ... Arecibo_radio unknown
   MobyDick 149.687  32.7203 ... Arecibo_radio unknown
        ...     ...      ... ...           ...     ...
    Odyssey 248.581    19.72 ... Arecibo_radio unknown
    Catch22 348.555    4.915 ... Arecibo_radio unknown
    Catch22 348.621  4.50717 ... Arecibo_radio unknown
    Catch22 348.644  4.49844 ... Arecibo_radio unknown
    Catch22 348.697  4.63995 ... Arecibo_radio unknown
    Catch22 348.777   4.3732 ... Arecibo_radio unknown
    Catch22 348.874  4.61326 ... Arecibo_radio unknown
       AnaK 353.779 0.301059 ... Arecibo_radio unknown
       AnaK 354.195 0.623424 ... Arecibo_radio unknown
       AnaK 354.351 0.390803 ... Arecibo_radio unknown

# Matching Data files to Spec data -- USING COORDS WITHIN A RANGE 
#### This part is Palomar May2015 *now matched-names-w/coords* 

In [21]:
#first need to mask name-matched-data w/coords to enable code to run
names2_may15_palomar = names_may15_palomar.filled(fill_value=-999)

#converts names2_may15_palomar table's ra&dec into degrees via skycoord
sc_may15 = SkyCoord(ra=names2_may15_palomar['RA'], dec=names2_may15_palomar['DEC'], unit=(u.hour, u.deg))

#adding skycoord coords into table to use with matching b/c skycoord is made to do this
names2_may15_palomar['coordinates'] = sc_may15

In [22]:
#actual matching by coords code

#un-masking spec_data table
spec_data2 = spec_data.filled(fill_value=-999)

#telling where coords to match are
ra2 = spec_data2['RA']
dec2 = spec_data2['DEC']

catalog = SkyCoord(ra=ra2*u.degree, dec=dec2*u.degree) #from spectral data
#this actualy does the matching
names_may15_palomar_matches = names2_may15_palomar['coordinates'].match_to_catalog_sky(catalog)

#print ('***********************check these in SDSS!**************************************')
names_may15_palomar_matches #palomar matches to fiber spectra table 

#NOTE can call above matches for each of these arrays then [0][i] for ith item in the array
#names_coord_matches[0] = rows for catalog of matches
#names_coord_matches[1] = the on sky angle separation for closest matches
#names_coord_matches[2] = the 3D distance between closest matches


#setting up to match with all spec data,not subset 

spec_data_all2 = spec_data_all.filled(fill_value=-999)
ra3 = spec_data_all2['RA']
dec3 = spec_data_all2['DEC']
fullcatalog = SkyCoord(ra=ra3*u.degree, dec=dec3*u.degree)
names_may15_palomar_matches_fullcat = names2_may15_palomar['coordinates'].match_to_catalog_sky(fullcatalog)


In [23]:
#checking matches to within 1 arcsec 
d2d = names_may15_palomar_matches[1]
subset_may15 = np.where(d2d<(1*u.arcsec))
subset_may15 #again this is a small # of matches within 1" NO ITS NOT THERE *SHOULD* BE ONLY 3!!!
#these are the rows in names2_may15_palomar that matched with spec_data2!!!!

(array([43, 44, 45]),)

In [24]:
#these are rows in palomar may2015 data that matched ra&decs in spec_data2 to within 1"
names2_may15_palomar[43:46] 

<Table length=3>
  ID        RA      ...              coordinates             
                    ...                deg,deg               
str40     str13     ...                 object               
----- ------------- ... -------------------------------------
 ody2  16 31 30.573 ... 247.87738749999994,20.093624833333333
 ody4 16 32 36.4991 ...  248.15207958333335,19.81025913888889
 ody7 16 32 39.2224 ... 248.16342666666665,19.792207583333337

In [25]:
#quick verification of matches to spec_data2
names_may15_palomar_matches_test = catalog.match_to_catalog_sky(names2_may15_palomar['coordinates'])

#names_may15_palomar_matches_test
d2d_test = names_may15_palomar_matches_test[1]
subset_may15_test = np.where(d2d_test<(1*u.arcsec))
subset_may15_test

(array([ 99, 100, 101]),)

In [26]:
print ('yup these match above coords within 1"!')
print (spec_data2[99:102])

yup these match above coords within 1"!
       OBJID              RA           DEC      ... SPEC_HA_EW SPEC_HA_EWERR
------------------- ------------- ------------- ... ---------- -------------
1237662224092364842 247.877387573 20.0936248407 ...      -99.0         -99.0
1237662698115433445  248.16342684  19.792207594 ...      -99.0         -99.0
1237662698115432783 248.152079686 19.8102591366 ...      -99.0         -99.0


#### This part is Palomar May2017 *now matched-names-w/coords* 

In [27]:
#converts names_may17_palomar table's ra&dec into degrees via skycoord
sc_may17 = SkyCoord(ra=names_may17_palomar['RA'], dec=names_may17_palomar['DEC'], unit=(u.hour, u.deg))

#adding skycoord coords into table to use with matching b/c skycoord is made to do this
names_may17_palomar['coordinates'] = sc_may17

#most setup in palomar_may17 above so can just type this line b/c defs are above
names_may17_palomar_matches = names_may17_palomar['coordinates'].match_to_catalog_sky(catalog)
#names_may17_palomar_matches[0]

#checking matches to within 1 arcsec 
d2d_may17 = names_may17_palomar_matches[1]
subset_may17 = np.where(d2d_may17<(1*u.arcsec))
subset_may17 

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]),)

In [28]:
names_may17_palomar[0:33] #these are the names rows that matched in spec_data2 to within 1"

<Table length=33>
           ID            ...              coordinates              
                         ...                deg,deg                
         str100          ...                 object                
------------------------ ... --------------------------------------
     48721248845970-Dune ... 221.3161158333333,-0.15993708333333334
    50372092690464-Alice ...  180.2954420833333,-1.2976838333333331
    50372092690464-Alice ...  180.2954420833333,-1.2976838333333331
    50372092690464-Alice ...  180.2954420833333,-1.2976838333333331
    50372092690464-Alice ...  180.2954420833333,-1.2976838333333331
 57607497318756-StarTrek ...    123.2431733333333,36.19835997222222
 57607497515484-StarTrek ...   123.64989749999997,36.43435538888888
  62224092496776-Odyssey ...        248.19536875,19.867012666666668
  62662147310256-Odyssey ...   247.8258920833333,20.210878777777776
                     ... ...                                    ...
       67287812735027-Oz ...   157.77827416666668,28.79664480555556
       67287812735027-Oz ...   157.77827416666668,28.79664480555556
68298203070473-ScoobyDoo ...  182.42804416666664,20.046918750000003
68298203070473-ScoobyDoo ...  182.42804416666664,20.046918750000003
68298203267092-ScoobyDoo ...  182.99066666666664,20.027848694444444
68298203267092-ScoobyDoo ...  182.99066666666664,20.027848694444444
68298203267092-ScoobyDoo ...  182.99066666666664,20.027848694444444
  79005021831220-Catch22 ...        348.64381625,4.4984435000000005
 79996084617517-OBrother ...       335.97997625,-3.2705485833333334
 80066954264778-OBrother ...   335.8363054166666,-3.659802638888889

#### This part is Palomar Nov2015 *now matched-names-w/coords* 

In [29]:
#un-masking table
names_nov15_palomar_fixed = names_nov15_palomar.filled(fill_value=999)

#converts names_nov15_palomar table's ra&dec into degrees via skycoord
sc_nov15 = SkyCoord(ra=names_nov15_palomar_fixed['RA'], dec=names_nov15_palomar_fixed['DEC'], unit=(u.hour, u.deg))

#adding skycoord coords into table to use with matching b/c skycoord is made to do this
names_nov15_palomar_fixed['coordinates'] = sc_nov15


#this actualy does the matching
names_nov15_palomar_matches = names_nov15_palomar_fixed['coordinates'].match_to_catalog_sky(catalog)

#checking matches to within 1 arcsec 
d2d_nov15 = names_nov15_palomar_matches[1]
subset_nov15 = np.where(d2d_nov15<(1*u.arcsec))
subset_nov15

(array([ 0,  1,  2,  7,  8,  9, 14]),)

In [30]:
#is this a saga satellite tho? - its def a satellite, but host coords dont appear in saga paper so ok not include
names_nov15_palomar_fixed[3:7] 


<Table length=4>
    ID         RA     ...    exp_time                 coordinates             
                      ...                               deg,deg               
  str44      str13    ...     str14                      object               
--------- ----------- ... -------------- -------------------------------------
Beowulf_1 09 06 00.93 ...            900 136.50387499999997,25.469916666666666
Beowulf_2 09 07 08.29 ...            300          136.78454166666666,25.342575
Beowulf_3 09 06 00.94 ...            600 136.50391666666664,25.375994444444444
Beowulf_4 09 06 12.49 ... 600(420oflost) 136.55204166666664,25.783622222222224

In [31]:
#all matched rows
t1_nov15_palomar = names_nov15_palomar_fixed[0:3]
t2_nov15_palomar = names_nov15_palomar_fixed[7:10]
t3_nov15_palomar = names_nov15_palomar_fixed[14:15]

#cant make all rows into one table - mixin column problems??
#table_nov15 = vstack([t1_nov15_palomar, t2_nov15_palomar, t3_nov15_palomar])
#table_nov15

#### This part is Keck Deimos --sept13 & sept14 & may15-- 

In [32]:
#gonna join all deimos tables
from astropy.table import Table, vstack
obs1 = sept13_deimos_table
obs2 = sept14_deimos_table
obs3 = may15_deimos_table
#obs4 = marapr2016_deimos #couldnt add, will do separately later
deimos_most = vstack([obs1, obs2, obs3])
#deimos_all = vstack([obs1, obs2, obs3, obs4]) #this gives mixin column problems wtf?

#removing an error value that was in RA column preventing matching - just an alignment neway
check = np.where(deimos_most['RA'] != '!KeyError!')
deimos_most_fixed = deimos_most[check]

#first insert skycoords to do ra&dec conversions
sc_deimos = SkyCoord(ra=deimos_most_fixed['RA'], dec=deimos_most_fixed['DEC'], unit=(u.hour, u.deg))
#adding skycoord coords into table to use with matching b/c skycoord is made to do this
deimos_most_fixed['coordinates'] = sc_deimos
#deimos_most_fixed

In [33]:
#most setup in palomar_may17 above so can just type this line b/c defs are above
deimos_most_fixed_matches = deimos_most_fixed['coordinates'].match_to_catalog_sky(catalog)
deimos_most_fixed_matches[0]

array([105, 105, 105, 106, 104, 104, 103, 100, 100, 100, 118, 118, 118,
       118,  22,  23,  23,  23,   3,   3, 104, 104, 104, 104, 104, 104,
       100, 100, 118, 118,  22,  22,  22,  23,   3,   3,  25,  25,  25,
        25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,
        25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,
        25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,
        25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,
        98,  98,  98,  98,  98,  98,  99, 166, 166, 103, 103, 103, 103,
       102, 102, 102,  22,  22,  22,  22,  22,  22,  22,  22,  22,  22,
        22,  22,  22,  22,  22,  22,  22,  22,  22,  22,  22,  22,  22,
        22,  22,  22,  22,  22,  22,  22,  22,  22,  22,  22,  22,  22,
        22,  22,  22,  31,  31,  31,  31,  25,  30,  30,  30,  30,  30,
        11,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,
        25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  2

In [34]:
#checking matches to within a certain radius #min radius of 2" to get 3 matches
d2d_deimos = deimos_most_fixed_matches[1]
subset_deimos = np.where(d2d_deimos<(3*u.arcsec)) #sticking with 3" to give 15 matches, 9" gives 18 matches tho,10"=22 matches
subset_deimos #this is def missing some targets (ex 97) - approx 95 should be saga tho

(array([104, 105, 106, 200, 201, 202, 203, 204, 205, 206, 243, 244, 245,
        246, 247]),)

In [35]:
#104, 105, 106, 200, 201, 202, 203, 204, 205, 206, 243, 244, 245,
#        246, 247
#deimos_1 = deimos_most_fixed[104:107]
#deimos_2 = deimos_most_fixed[200:207]
#deimos_3 = deimos_most_fixed[243:248]

In [36]:
deimos_most_fixed[209]

<Row index=209>
   Date          ID            RA         DEC     Exp_time  Instrument             coordinates             
                                                                                     deg,deg               
  str36        str116        str44       str48     str84      str44                   object               
--------- --------------- ----------- ----------- -------- ----------- ------------------------------------
5-17-2015 ""Star_Trek_2"" 08:12:59.00 +36:11:52.6      200 Keck_deimos 123.24583333333331,36.19794444444444

In [37]:
#testing matching with fullcatalog to see if same result
deimos_most_fixed_matches_fullcat = deimos_most_fixed['coordinates'].match_to_catalog_sky(fullcatalog)
#print (len(deimos_most_fixed_matches_fullcat[0])) #251 same as deimos_most_fixed
d2d_deimos_test = deimos_most_fixed_matches_fullcat[1]
subset_deimos_fullcat = np.where(d2d_deimos_test<(3*u.arcsec)) 
subset_deimos_fullcat
#this isnt good theres 3 more matches than with the subset BUT it includes 97
#deimos_most_fixed[97]

(array([ 97, 104, 105, 106, 148, 149, 200, 201, 202, 203, 204, 205, 206,
        243, 244, 245, 246, 247]),)

In [38]:
#testing non matches that shouldve
print ('these are the spec_all rows that should match deimos rows in cell below:', deimos_most_fixed_matches_fullcat[0][0:7])
print ('this is 42254:',spec_data_all2['RA','DEC','SATS','REMOVE'][42254])
print ('this is 42344:',spec_data_all2['RA','DEC','SATS','REMOVE'][42344])
print ('this is 41425:',spec_data_all2['RA','DEC','SATS','REMOVE'][41425])
print ('this is 41993:',spec_data_all2['RA','DEC','SATS','REMOVE'][41993])
print ('these are the spec_all rows that should match deimos rows in cell below:', deimos_most_fixed_matches_fullcat[0][9])
print ('this is 41427:',spec_data_all2['RA','DEC','SATS','REMOVE'][41427])
print ('these are the spec_all rows that should match deimos rows in cell below:', deimos_most_fixed_matches_fullcat[0][22:28])
print ('this is 41425:',spec_data_all2['RA','DEC','SATS','REMOVE'][41425])
print ('this is 42300:',spec_data_all2['RA','DEC','SATS','REMOVE'][42300])
print ('this is 40939:',spec_data_all2['RA','DEC','SATS','REMOVE'][40939])
print ('this is 42145:',spec_data_all2['RA','DEC','SATS','REMOVE'][42145])
print ('these are the spec_all rows that should match deimos rows in cell below:', deimos_most_fixed_matches_fullcat[0][98:104])
print ('this is 65746:',spec_data_all2['RA','DEC','SATS','REMOVE'][65746])
print ('this is 41334:',spec_data_all2['RA','DEC','SATS','REMOVE'][41334])
print ('these are the spec_all rows that should match deimos rows in cell below:', deimos_most_fixed_matches_fullcat[0][207:210])
print ('this is 3700:',spec_data_all2['RA','DEC','SATS','REMOVE'][3700])
print ('these are the spec_all rows that should match deimos rows in cell below:', deimos_most_fixed_matches_fullcat[0][248])
print ('this is 7758:',spec_data_all2['RA','DEC','SATS','REMOVE'][7758])

these are the spec_all rows that should match deimos rows in cell below: [42254 42254 42254 42344 41425 41425 41993]
this is 42254:       RA           DEC      SATS REMOVE
------------- ------------- ---- ------
247.855690028 20.1434809452    0     -1
this is 42344:       RA           DEC      SATS REMOVE
------------- ------------- ---- ------
248.407789245 19.9097245973    0     -1
this is 41425:      RA           DEC      SATS REMOVE
------------ ------------- ---- ------
248.02863847 19.6926603699    0     -1
this is 41993:       RA           DEC      SATS REMOVE
------------- ------------- ---- ------
248.342933442 19.4571322728    0     -1
these are the spec_all rows that should match deimos rows in cell below: 41427
this is 41427:      RA           DEC      SATS REMOVE
------------ ------------- ---- ------
248.19457473 19.7825594351    0     -1
these are the spec_all rows that should match deimos rows in cell below: [41425 42300 42300 40939 42145 42145]
this is 41425:      RA  

In [39]:
#print (deimos_most_fixed[0:7])
#print (deimos_most_fixed[9])
#print (deimos_most_fixed[22:28])
#print (deimos_most_fixed[98:104])
#print (deimos_most_fixed[207:210])
deimos_most_fixed[248]

<Row index=248>
   Date       ID          RA         DEC     Exp_time  Instrument         coordinates         
                                                                            deg,deg           
  str36     str116      str44       str48     str84      str44               object           
--------- ---------- ----------- ----------- -------- ----------- ----------------------------
5-17-2015 ""AnaK_2"" 23:36:47.34 +00:37:33.1      200 Keck_deimos 354.19725,0.6258611111111111

In [40]:
print ("this is row number of full cat data that will match deimos data row:", deimos_most_fixed_matches_fullcat[0][97])
print (spec_data_all2['RA', 'DEC','HOST_SAGA_NAME','SATS', 'REMOVE'][42648])
print ('this is deimos row 97 that should match above', deimos_most_fixed['ID','Date','coordinates'][97])
print ('ask erik b/c i think 97 should be a sat but its sats value is 2 not 1...mistake? - this is why fullcat/selected cat differs too')
print ('below has same problem but are DEF NOT saga even tho it is a galaxy')
print ("this is row number of full cat data that will match deimos data row:", deimos_most_fixed_matches_fullcat[0][148])
print ('this is 19766:', spec_data_all2['RA', 'DEC','HOST_SAGA_NAME','SATS', 'REMOVE'][19766])
print ("this is row number of full cat data that will match deimos data row:", deimos_most_fixed_matches_fullcat[0][149])
print ("this is deimos rows that should match 19766:", deimos_most_fixed['ID', 'coordinates'][148:150])

this is row number of full cat data that will match deimos data row: 42648
      RA           DEC      HOST_SAGA_NAME SATS REMOVE
------------- ------------- -------------- ---- ------
247.306083596 19.8387073369         147100    2     -1
this is deimos row 97 that should match above   ID     Date           coordinates         
                          deg,deg           
----- --------- ----------------------------
ody_6 9-23-2014 247.30675,19.838638888888887
ask erik b/c i think 97 should be a sat but its sats value is 2 not 1...mistake? - this is why fullcat/selected cat differs too
below has same problem but are DEF NOT saga even tho it is a galaxy
this is row number of full cat data that will match deimos data row: 19766
this is 19766:       RA            DEC       HOST_SAGA_NAME SATS REMOVE
------------- --------------- -------------- ---- ------
39.1199202588 -0.974926414101         132339    2     -1
this is row number of full cat data that will match deimos data row: 19766
th

In [41]:
#testing still to get matching row numbers in full catalog
deimos_most_fixed_reverse_test = fullcatalog.match_to_catalog_sky(deimos_most_fixed['coordinates'])
#for i in deimos_most_fixed_reverse_test[0]:
#    print (i)
d2d_deimos_full = deimos_most_fixed_reverse_test[1]
subset_deimos_full = np.where(d2d_deimos_full<(3*u.arcsec))
print (subset_deimos_full)
print ("this is row number of deimos data that will match full catalog row:", deimos_most_fixed_reverse_test[0][3884])
print('this is that deimos row (204):')
print (deimos_most_fixed['ID', 'coordinates'][204])
print ('this is full catalog row 3884:')
print (spec_data_all['RA','DEC'][3884])
print ('great the matching works b/c above do match...but still not enough overall matches')

(array([ 3884,  5949, 19766, 31819, 41108, 41249, 42648]),)
this is row number of deimos data that will match full catalog row: 204
this is that deimos row (204):
       ID                   coordinates             
                              deg,deg               
--------------- ------------------------------------
""Star_Trek_1"" 123.65066666666664,36.43402777777777
this is full catalog row 3884:
      RA           DEC     
------------- -------------
123.649897556 36.4343553979
great the matching works b/c above do match...but still not enough overall matches


In [42]:
#could delete b/c did in print stmts above
#examples of some targets that should have matched to catalog but didnt
#deimos_most_fixed[97:99]

In [43]:
#plt.hist(d2d_deimos.arcsec, range=(0,20), bins=25)

In [44]:
#gonna test these in sdss

#commented out b/c dont really need these popping up every time i run the NB
#import webbrowser
#urltempl = 'http://skyserver.sdss.org/dr13/en/tools/chart/navi.aspx?ra={}&dec={}'
#for sc0 in sc_deimos[104:107]:
#    webbrowser.open_new_tab(urltempl.format(sc0.ra.deg, sc0.dec.deg))
print ('great these are all galaxies!')

great these are all galaxies!


In [45]:
#collecting table rows that did match within 3"
deimos_1 = deimos_most_fixed[104:107]
deimos_2 = deimos_most_fixed[200:207]
deimos_3 = deimos_most_fixed[243:248]
#deimos_some_matches = vstack([deimos_1, deimos_2, deimos_3]) #still cant b/c mixin columns


In [46]:
#could delete b/c idk what this was, think its repeated in print stmts above neways
#find the new deimos_most_fixed row number
#testing what SHOULD be a match to see how far the RA&DECs are
#print (spec_data2['RA', 'DEC'][98])
#print (deimos_most_fixed[97]) #sdss confirmed galaxy...but still SAGA? theyre pretty far apart
#print ('possibly just really bad pointing??')

In [47]:
#can delete, did in print stmts above
#example of what should be a match but didnt match 
#deimos_most_fixed[0] #sdss confirmed galaxy...saga tho?

In [48]:
#trying another SHOULD be match for one of the deimos datafiles

#removing an error value that was in RA column preventing matching (for a leo mask aka non saga anyway)
checking = np.where(obs3['RA'] != '!KeyError!')
obs3 = obs3[checking]

#adding coords
sc_obs3_test = SkyCoord(ra=obs3['RA'], dec=obs3['DEC'], unit=(u.hour, u.deg))
obs3['coordinates'] = sc_obs3_test

#gonna match against full fiber spec file jic
#ra3 = spec_data_all['RA']
#dec3 = spec_data_all['DEC']

#fullcatalog = SkyCoord(ra=ra3*u.degree, dec=dec3*u.degree) #from full spectral data

obs3_matches = obs3['coordinates'].match_to_catalog_sky(fullcatalog)

#checking matches to within a certain radius 
d2d_obs3 = obs3_matches[1]
subset_obs3 = np.where(d2d_obs3<(3*u.arcsec))
print (subset_obs3)
print ('good! 95 showed up')

(array([49, 50, 51, 52, 53, 54, 55, 92, 93, 94, 95, 96]),)
good! 95 showed up


In [49]:
#testing reverse matching of above cell
obs3_matches2 = fullcatalog.match_to_catalog_sky(obs3['coordinates'])
d2d_obs3_2 = obs3_matches2[1]
subset_obs3_2 = np.where(d2d_obs3_2<(3*u.arcsec))
print (subset_obs3_2)
print ('why arent there the same number of matches as above cell?')

(array([ 3884,  5949, 31819, 41108]),)
why arent there the same number of matches as above cell?


#### This part is Keck Deimos --marapr16--

In [50]:
#first insert skycoords to do ra&dec conversions
sc_deimos_marapr = SkyCoord(ra=marapr2016_deimos['RA'], dec=marapr2016_deimos['DEC'], unit=(u.hour, u.deg))
#adding skycoord coords into table to use with matching b/c skycoord is made to do this
marapr2016_deimos['coordinates'] = sc_deimos_marapr

#most setup in palomar_may17 above so can just type this line b/c defs are above
deimos_marapr_matches = marapr2016_deimos['coordinates'].match_to_catalog_sky(catalog)
deimos_marapr_matches[0]



array([  7,   7,   7,  18,  18,  18,  18,  18,  18,  18,  18,  18,  18,
        18,  18, 131, 131, 131, 163, 163, 163, 163, 163, 163, 166, 166,
       166, 166, 166, 166, 103, 103, 103,  18,  18,  18,   7,   7,   7,
         7,   7,   7,   7,   7,   7,   7,   7,   7,   7,  11,  11,  11,
        11, 163, 163])

In [51]:
#checking against full catalog
deimos_marapr_matches_fullcat = marapr2016_deimos['coordinates'].match_to_catalog_sky(fullcatalog)
deimos_marapr_matches_fullcat[0]

array([ 3555,  3555,  3555, 11024, 11024, 11024, 11539, 11539, 11539,
       11340, 11340, 11340, 11322, 11322, 11322, 52121, 52121, 52121,
       60460, 60460, 60460, 60653, 60653, 60653, 66475, 66475, 66475,
       66596, 66596, 66596, 41577, 41577, 41577, 11739, 11739, 11739,
        4349,  4349,  4349,  4349,  4349,  3736,  3736,  3736,  3736,
        3736,  3550,  3550,  3550,  7497,  7497,  7497,  7497, 60862, 60862])

In [52]:
#checking for problems with rows in full catalog that deimos matched to 
#spec_data_all2['RA', 'DEC','HOST_SAGA_NAME','SATS', 'REMOVE'][3555] #sats=0
#spec_data_all2['RA', 'DEC','HOST_SAGA_NAME','SATS', 'REMOVE'][11024] #sats=0
#spec_data_all2['RA', 'DEC','HOST_SAGA_NAME','SATS', 'REMOVE'][11539] #sats=0
spec_data_all2['RA', 'DEC','HOST_SAGA_NAME','SATS', 'REMOVE'][60862] #sats=0




<Row index=60862>
      RA            DEC       HOST_SAGA_NAME  SATS REMOVE
   float64        float64         str48      int64 int64 
------------- --------------- -------------- ----- ------
221.402849914 -0.344594406822         165536     0     -1

In [53]:
#checking results w/ sdss
#spec_data2['RA','DEC','SATS','REMOVE'][7] #this is a star trek satellite

In [54]:
#checking results w/ sdss
#marapr2016_deimos[0:4] #sdss says ST3 is a star so why labeled ST3????
#sdss says MD1 is a star so why labeled MD1 (thought moby_dick_1)?

In [55]:
#checking results w/ sdss
#spec_data2['RA','DEC','SATS','REMOVE'][18] #this is also a galaxy but pretty far from MD1

In [56]:
#marapr2016_deimos

In [57]:
#checking fullcat matches to within a certain radius (11" is the min radius to get any hits)
d2d_deimos_marapr_fullcat = deimos_marapr_matches_fullcat[1]
subset_deimos_marapr_fullcat = np.where(d2d_deimos_marapr_fullcat<(59*u.arcsec)) # 46 matches at 59"
print (subset_deimos_marapr_fullcat) #ideally 46 matches
print ('this isnt that bad except every row in fullcat that matches contains SATS = 0 and thats why these are still all bad')

(array([ 0,  1,  2,  3,  4,  5, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54]),)
this isnt that bad except every row in fullcat that matches contains SATS = 0 and thats why these are still all bad


In [58]:
#checking selected-catalog matches to within a certain radius (58" is the min radius to get any hits)
d2d_deimos_marapr = deimos_marapr_matches[1]
subset_deimos_marapr = np.where(d2d_deimos_marapr<(1*u.arcmin)) #34 hits at 20', 31 at 15'
subset_deimos_marapr #also very bad...marapr16 should ALL be saga

(array([15, 16, 17]),)

In [59]:
#checking selected match results w/ sdss
marapr_deimos_1arcmin = marapr2016_deimos[15:18] #no!  sdss says this is a star (3 matches within 1')
print (marapr_deimos_1arcmin)
print ("above deimos should match below fiber spec but its a star not galaxy ==========> ZERO deimos matches??!!???")
print (spec_data2['RA','DEC'][131])

 ID      RA         DEC      Instrument              coordinates             
                                                       deg,deg               
--- ----------- ----------- ----------- -------------------------------------
MMT 12:11:27.40 +20:03:26.5 Keck_deimos 182.86416666666665,20.057361111111113
MMT 12:11:27.40 +20:03:26.5 Keck_deimos 182.86416666666665,20.057361111111113
MMT 12:11:27.40 +20:03:26.5 Keck_deimos 182.86416666666665,20.057361111111113
above deimos should match below fiber spec but its a star not galaxy ==========> ZERO deimos matches??!!???
      RA           DEC     
------------- -------------
182.848206846 20.0632227672


In [60]:
#print ('these are the spec_all rows that should match deimos rows in cell below:', deimos_marapr_matches_fullcat[0][248])
#print ('this is 7758:',spec_data_all2['RA','DEC','SATS','REMOVE'][7758])

In [61]:
print ('CONCLUSION: after many tests, deimos-MarApr really has no satellite matches.?')

CONCLUSION: after many tests, deimos-MarApr really has no satellite matches.?


#### This part is Arecibo radio data

In [62]:
#didnt need to do this ALREADY IN DEGREES!!!!!!! 


#first convert ra & dec into degrees & add to table
#sc_radio = SkyCoord(ra=radio_data_table['RA'], dec=radio_data_table['DEC'], unit=(u.hour, u.deg))
#radio_data_table['coordinates'] = sc_radio

ra1 = radio_data_table['RA']
dec1 = radio_data_table['DEC']
c = SkyCoord(ra=ra1*u.degree, dec=dec1*u.degree)

#most setup in palomar_may17 above so can just type this line b/c defs are above
radio_data_table_matches = c.match_to_catalog_sky(catalog)

radio_data_table_matches[0]


array([ 22,  24,  23,  26,  25,  31,  30,   7,   8,  18,  49,  51,  53,
        52,  50,  82,  83,  83,  83, 129, 132, 131, 130, 163, 165, 166,
        98, 105,  99, 104, 101, 100, 102, 106, 103, 118, 121, 120, 119,
       116, 117,  13,  12,  11])

In [63]:
#checking what Alice, Soprano matched to in selected-catalog b/c in fullcatalog they matched SATS=0
radio_data_table_matches[0][17]


spec_data2['RA','DEC','SATS','REMOVE'][83] 

<Row index=83>
     RA           DEC       SATS REMOVE
  float64       float64    int64 int64 
------------ ------------- ----- ------
180.29544216 -1.2976838319     1     -1

In [64]:
#checking matches to within specific radius
#for selected-catalog matches(30 hits within 1", 42 hits within 4", 43 hits at 10', need all 44 to match this happens at 197')
d2d_radio = radio_data_table_matches[1]
subset_radio = np.where(d2d_radio<(4*u.arcsec))
print (subset_radio[0])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43]


In [65]:
#checking non-matches
radio_data_table[17:19] #why didnt these match- def SAGA, Alice sdss-galaxy, 
#Sopranos sdss-galaxy BUT i dont see anything at those coords except can see sopranos(host) nearby at coords given in paper

<Table length=2>
   ID       RA     DEC    HI_data_source   Instrument    Date 
 str11   float64 float64      str50          str13       str7 
-------- ------- -------- -------------- ------------- -------
   Alice 180.419 -1.20277           none Arecibo_radio unknown
Sopranos 180.636  1.95803           none Arecibo_radio unknown

In [66]:
#matching to fullcatalog now
radio_data_table_matches_fullcat = c.match_to_catalog_sky(fullcatalog)
radio_data_table_matches_fullcat[0]
#spec_data_all2['RA','DEC','SATS','REMOVE'][65201] #problem is SATS = 0


array([14444, 15144, 15115, 15525, 15498, 18415, 17870,  3700,  3884,
       11624, 24211, 24629, 24700, 24635, 24484, 31275, 31819, 32533,
        1373, 51735, 52154, 52120, 51755, 61125, 65599, 67082, 40574,
       41548, 40876, 41428, 41108, 41083, 41249, 42350, 41334, 47233,
       47640, 47630, 47561, 46685, 46740,  7991,  7758,  5949])

In [67]:
#checking what columns values are for matched to fullcatalog rows
#spec_data_all2['RA','DEC','SATS','REMOVE'][14444] #ok
#spec_data_all2['RA','DEC','SATS','REMOVE'][15144] #ok
#spec_data_all2['RA','DEC','SATS','REMOVE'][15525] #ok
#spec_data_all2['RA','DEC','SATS','REMOVE'][31819] #ok
#spec_data_all2['RA','DEC','SATS','REMOVE'][32533] #SATS = 0, this is Alice that didnt match until 10'
#spec_data_all2['RA','DEC','SATS','REMOVE'][1373] #SATS = 0, this is Sopranos above which idk if real anyway
spec_data_all2['RA','DEC','SATS','REMOVE'][5949] #ok

<Row index=5949>
      RA           DEC        SATS REMOVE
   float64       float64     int64 int64 
------------- -------------- ----- ------
354.350599991 0.390802769345     1     -1

In [68]:
#checking how close are the matches with fullcatalog
#row 17(alice) matches at 66" & row 18(sopranos) matches at 100"
d2d_radio_fullcat = radio_data_table_matches_fullcat[1]
subset_radio_fullcat = np.where(d2d_radio_fullcat<(4*u.arcsec))
print (subset_radio_fullcat)
print ('these are the same')

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43]),)
these are the same


In [69]:
#collecting all those matches to fullcat (except the 2 that have sats=0) within 4"
radio_1 = radio_data_table[0:17]
radio_2 = radio_data_table[19:44]

In [70]:
#RECHECK THESE COORDS AFTER FIXED HMS TO DEGREES idk what this cell is about

#checking against sdss
print (radio_data_table[11:13]) #11 is a galaxy, no object detected here w/ sdss(bad pointing?)
print ('------------------------above should match with below fiber spec----------------------')
print (spec_data2['RA', 'DEC'][20]) #def a galaxy but not same as 11 above
print (' ************************************************************************************ ')
print (radio_data_table[17]) #sdss labeled galaxy but idk
print ('-------------------------above should match with below fiber spec---------------------')
print (spec_data2['RA', 'DEC'][85]) #def a galaxy but not same as 17 above

 ID    RA     DEC   HI_data_source   Instrument    Date 
--- ------- ------- -------------- ------------- -------
 Oz 158.043 28.4831          a3118 Arecibo_radio unknown
 Oz 158.089 28.4199          a3118 Arecibo_radio unknown
------------------------above should match with below fiber spec----------------------
      RA           DEC     
------------- -------------
209.375005785 29.0581355972
 ************************************************************************************ 
  ID     RA     DEC    HI_data_source   Instrument    Date 
----- ------- -------- -------------- ------------- -------
Alice 180.419 -1.20277           none Arecibo_radio unknown
-------------------------above should match with below fiber spec---------------------
      RA           DEC      
------------- --------------
187.241509345 -1.60302487082


# These are the final tables of saga observations from each log

In [88]:
#palomar tables to within 1"
FT_1 = t1_nov15_palomar
FT_2 = t2_nov15_palomar
FT_3 = t3_nov15_palomar
FT_4 = names2_may15_palomar[43:46]
FT_5 = names_may17_palomar[0:33] 

#deimos tables to within 3"
#no matches until go out to within 10 arcmins, unsure of where to make cut; still result multiple table selections
#not sure why above comment is no longer valid....jupyter nb too long problems?
FT_6 = deimos_1
FT_7 = deimos_2
FT_8 = deimos_3
# closest matches (marapr_deimos_1arcmin) are all stars! MarApr_deimos really has no matches??..verify names w/erik


#arecibo radio table to within 4"
FT_9 = radio_1
FT_10 = radio_2

print ('arecibo & palomar & deimos tables saved in google sheets:')
print ('https://docs.google.com/spreadsheets/d/1jBr_25t8rd7jW2mmRmouOempmlA5PMNhgDs00xx1ic0/edit?usp=sharing')



arecibo & palomar & deimos tables saved in google sheets:
https://docs.google.com/spreadsheets/d/1jBr_25t8rd7jW2mmRmouOempmlA5PMNhgDs00xx1ic0/edit?usp=sharing


In [72]:
#didnt need b/c this didnt help like i thought it would
#np.savetxt('FT_1.txt', t1_nov15_palomar, fmt='%s', header="ID, RA, DEC, Date, Instrument, coordinates")
#np.savetxt('FT_2.txt', t2_nov15_palomar, fmt='%s', header="ID, RA, DEC, Date, Instrument, coordinates")
#np.savetxt('FT_3.txt', t3_nov15_palomar, fmt='%s', header="ID, RA, DEC, Date, Instrument, coordinates")
#np.savetxt('FT_4.txt', names2_may15_palomar[43:46], fmt='%s', header="ID, RA, DEC, Date, Instrument, coordinates")
#np.savetxt('FT_5.txt', names_may17_palomar[0:33], fmt='%s', header="ID, RA, DEC, Date, Instrument, coordinates")


#### Writing all tables to a file to upload on google doc for team---tables 1-4 had problems tho

In [73]:
#this will write a single table to file...but i have multiple and cant vstack
table_to_write = FT_8['ID', 'Date', 'Exp_time','Instrument']
table_to_write['RA'] = FT_8['coordinates'].ra.deg
table_to_write['DEC'] = FT_8['coordinates'].dec.deg
table_to_write.write('FT_8_for_google_drive.csv')


In [74]:
#this has unsupported operand type(s) for +:'NoneType' and 'str' problems
table_to_write = FT_1['ID', 'Date', 'exp_time','Instrument']
table_to_write['RA'] = FT_1['coordinates'].ra.deg
table_to_write['DEC'] = FT_1['coordinates'].dec.deg
#table_to_write.write('FT_1_for_google_drive.csv')

In [75]:
#this has unsupported operand type(s) for +:'NoneType' and 'str' problems
table_to_write = FT_2['ID', 'Date', 'exp_time','Instrument']
table_to_write['RA'] = FT_2['coordinates'].ra.deg
table_to_write['DEC'] = FT_2['coordinates'].dec.deg
#table_to_write.write('FT_2_for_google_drive.csv')

In [76]:
##this has 'NoneType' and 'str' problems
table_to_write = FT_3['ID', 'Date', 'exp_time','Instrument']
table_to_write['RA'] = FT_3['coordinates'].ra.deg
table_to_write['DEC'] = FT_3['coordinates'].dec.deg
#table_to_write.write('FT_3_for_google_drive.csv')

In [77]:
#this has 'NoneType' and 'str' problems
table_to_write = FT_4['ID', 'Date', 'exp_time','Instrument']
table_to_write['RA'] = FT_4['coordinates'].ra.deg
table_to_write['DEC'] = FT_4['coordinates'].dec.deg
#table_to_write.write('FT_4_for_google_drive.csv')

In [78]:
table_to_write = FT_5['ID', 'Date', 'exp_time','Instrument']
table_to_write['RA'] = FT_5['coordinates'].ra.deg
table_to_write['DEC'] = FT_5['coordinates'].dec.deg
table_to_write.write('FT_5_for_google_drive.csv')

In [79]:
table_to_write = FT_6['ID', 'Date', 'Exp_time','Instrument']
table_to_write['RA'] = FT_6['coordinates'].ra.deg
table_to_write['DEC'] = FT_6['coordinates'].dec.deg
table_to_write.write('FT_6_for_google_drive.csv')

In [80]:
table_to_write = FT_7['ID', 'Date', 'Exp_time','Instrument']
table_to_write['RA'] = FT_7['coordinates'].ra.deg
table_to_write['DEC'] = FT_7['coordinates'].dec.deg
table_to_write.write('FT_7_for_google_drive.csv')

In [81]:
len(FT_4)

3

In [82]:
33 + 3 + 7 + 5 #all tables that printed to file

48

In [83]:
3 + 3 + 1 + 3 #all tables that didnt print to file

10

In [84]:
#JUST COPIED OVER TABLES INSTEAD OF WRITING TO FILE FOR FT_(1-4) ie THE ONES THAT HAD UNSUPPORTED OPERAND PROBLEMS
FT_4

<Table length=3>
  ID        RA      ...              coordinates             
                    ...                deg,deg               
str40     str13     ...                 object               
----- ------------- ... -------------------------------------
 ody2  16 31 30.573 ... 247.87738749999994,20.093624833333333
 ody4 16 32 36.4991 ...  248.15207958333335,19.81025913888889
 ody7 16 32 39.2224 ... 248.16342666666665,19.792207583333337

In [85]:
table_to_write = FT_9['ID', 'Date','HI_data_source','Instrument', 'RA','DEC']
#table_to_write['RA'] = FT_9['RA'].ra.deg
#table_to_write['DEC'] = FT_9['DEC'].dec.deg
table_to_write.write('FT_9_for_google_drive.csv')

In [86]:
table_to_write = FT_10['ID', 'Date','HI_data_source','Instrument', 'RA','DEC']
#table_to_write['RA'] = FT_9['RA'].ra.deg
#table_to_write['DEC'] = FT_9['DEC'].dec.deg
table_to_write.write('FT_10_for_google_drive.csv')

In [87]:
FT_3

<Table length=1>
    ID          RA     ... exp_time             coordinates             
                       ...                        deg,deg               
  str44       str13    ...  str14                  object               
---------- ----------- ... -------- ------------------------------------
MobyDick_1 09 58 44.92 ...      900 149.68716666666663,32.72026666666667